version: '2'

services:
  src:
    image: alpine:3.12.1
    command: ["uptime"]
    volumes:
      - src_html:/var/www

  elk-php81-fpm:
    image: elk-php81-fpm
    build:
      context: github.com/spuds/docker-elkarte.git#php81:php-fpm
    restart: always
    container_name: elkarte_php81
    volumes_from:
      - src

  elk-nginx:
    image: elk-nginx
    build:
      context: github.com/spuds/docker-elkarte.git#php81:nginx
    environment:
      - NGINX_ACCESS_LOG_FORMAT=timed
      - NGINX_FAST_CGI_PASS=elk-php81-fpm:9000
    container_name: elkarte_nginx81
    depends_on:
      - elk-php8-fpm
    volumes_from:
      - src
    ports:
      - 80:80

  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: elkarte
      MYSQL_USER: elkarte
      MYSQL_PASSWORD: elkarte
      MYSQL_DATABASE: elkarte
    restart: always
    container_name: elkarte_db8
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci'
    ]
    volumes:
      - db_data8:/var/lib/mysql
    expose:
      - 3306

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  sphinx:
    image: macbre/sphinxsearch:3.3.1
    container_name: elkarte_sphinx8
    ports:
      - "36307:9312"
      - "36308:9306"
    depends_on:
      - db
    volumes:
      - db_data8:/opt/sphinx/index
      - /tank/github/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    mem_limit: 512m

volumes:
    db_data8:
    src_html:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /tank/github
